server:
  port: 9290
  servlet:
    context-path: /travel-agent

spring:
  main:
    banner-mode: 'off'

  jackson:
    default-property-inclusion: non_empty
    property-naming-strategy: SNAKE_CASE

wiremock:
  server:
    port: 9291
    stubs: classpath:/stubs
    files: classpath:/stubs

travelagent:
  repository:
    endpoint: 'http://localhost:9291/bookings'
